update
plex-cluster-proxy working

diff --git a/plex-cluster-proxy/Dockerfile b/plex-cluster-proxy/Dockerfile
--- a/plex-cluster-proxy/Dockerfile
+++ b/plex-cluster-proxy/Dockerfile
@@ -1,12 +1,34 @@
-FROM nginx:alpine
-# For debugging
-#FROM firesh/nginx-lua:alpine
-RUN \
-    mkdir -p /data &&\
-    touch /var/log/nginx/plex.log &&\
-    chown nginx:nginx /data /var/log/nginx/plex.log &&\
-    apk --no-cache add openssl curl bash
-COPY ./config/nginx.conf /etc/nginx/nginx.conf.template
-COPY ./src /
-ENTRYPOINT ["/docker-entrypoint.sh"]
-CMD ["nginx", "-g", "daemon off;"]
+FROM s6on/debian
+
+ENV DEBIAN_FRONTEND noninteractive
+
+# update install
+RUN apt-get update -y && apt-get upgrade -y && \
+\
+# install nginx and dependancies
+    apt-get -y install nginx openssl curl gettext-base
+
+# Add user
+RUN useradd -U -d /config -s /bin/false nginx && \
+    usermod -G users nginx && \
+\
+# Setup directories
+    mkdir -p \
+    /data && \
+    touch /var/log/nginx/plex.log
+
+# Cleanup
+RUN apt-get -y autoremove && \
+    apt-get -y clean && \
+    rm -rf /var/lib/apt/lists/* && \
+    rm -rf /tmp/* && \
+    rm -rf /var/tmp/*
+
+# add local files
+COPY root/ /
+
+EXPOSE 32300 
+
+ENTRYPOINT ["/init"]
+HEALTHCHECK --interval=5s --timeout=2s --retries=20 CMD /healthcheck.sh || exit 1
+
