update
plex-cluster-proxy working

diff --git a/plex-cluster-manager/Dockerfile b/plex-cluster-manager/Dockerfile
--- a/plex-cluster-manager/Dockerfile
+++ b/plex-cluster-manager/Dockerfile
@@ -1,7 +1,25 @@
-FROM node:17-alpine
-COPY --chown=node:node src /app
-WORKDIR /app
-RUN apk add --no-cache --virtual .gyp python3 make g++ pkgconfig pixman-dev cairo-dev pango-dev
-RUN mkdir /data && chown node:node /data
-USER node
-CMD npm run prod
+FROM s6on/debian
+
+ENV DEBIAN_FRONTEND noninteractive
+
+# update install
+RUN apt-get update -y && apt-get upgrade -y && \
+\
+# install node.js and dependancies
+    apt-get -y install nodejs npm nuild-essential
+
+# Cleanup
+RUN apt-get -y autoremove && \
+    apt-get -y clean && \
+    rm -rf /var/lib/apt/lists/* && \
+    rm -rf /tmp/* && \
+    rm -rf /var/tmp/*
+
+# add local files
+COPY root/ /
+
+EXPOSE 32301 
+
+ENTRYPOINT ["/init"]
+HEALTHCHECK --interval=5s --timeout=2s --retries=20 CMD /healthcheck.sh || exit 1
+
